services:
  db:
    image: mysql:8.0
    container_name: inventory-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
      MYSQL_USER: app
      MYSQL_PASSWORD: app1234
    ports:
      - "3307:3306"
    volumes:
      - inventory_db:/var/lib/mysql

  backend:
    build: ./backend
    container_name: inventory-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/inventory?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app1234
    ports:
      - "8090:8090"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8090/api/inventory
    container_name: inventory-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"


volumes:
  inventory_db:
